import random

print("Welcome to the guess game where you need to find a random number generated by the computer")

def guess_the_number():
    guess_number = random.randint(1,10)
    user_guess = int(input("Type an integer number between 1 and 10: "))
    while user_guess != guess_number:
            user_guess = int(input("Type another time: ")) 
    print("You got the right answer!")
guess_the_number()
